/*
=========================================================
Database Initalization
Create Supabase tables: global_data and egypt_data
=========================================================
*/

create table if not exists public.global_data (
    id bigint generated by default as identity primary key,
    "Age" integer,
    "Gender" text,
    "Country" text,
    "Student_Working_Status" text,
    "Daily_Social_Media_Hours" numeric,
    "Screen_Time_Hours" numeric,
    "Night_Scrolling_Frequency" numeric,
    "Online_Gaming_Hours" numeric,
    "Content_Type_Preference" text,
    "Exercise_Frequency_per_Week" numeric,
    "Daily_Sleep_Hours" numeric,
    "Caffeine_Intake_Cups" numeric,
    "Study_Work_Hours_per_Day" numeric,
    "Overthinking_Score" numeric,
    "Anxiety_Score" numeric,
    "Mood_Stability_Score" numeric,
    "Social_Comparison_Index" numeric,
    "Sleep_Quality_Score" numeric,
    "Motivation_Level" numeric,
    "Emotional_Fatigue_Score" numeric,
    "Wellbeing_Index" numeric,
    "Burnout_Risk" text,
    "Sleep_Risk" text,
    "Reality_Risk" text,
    "Productivity_Risk" text,
    "Emotional_Risk" text,
    "SM_Usage" text,
    "Age_Group" text
);

create table if not exists public.egypt_data (
    id bigint generated by default as identity primary key,
    age text,
    gender text,
    status text,
    "daily screen time hours" text,
    "daily social media hours" text,
    "physical exercise" text,
    "sleep hour" text,
    "check phone morning" text,
    "irritable recently" text,
    "top apps" text,
    "ContentFormat_ID" text,
    "StayFactor_ID" text,
    "SkipPoint_KEY" text,
    "VisualEffect_Key" text,
    screen_time_level text,
    sleep_level text,
    doomscroll_category text,
    social_media_level text,
    high_screen_low_sleep integer,
    high_doomscroll_low_sleep integer
);

-- In Supabase Dashboard, datasets were uploaded using:
-- Table Editor - Insert - Import Data from CSV


-- Checks

-- after create tables
select count(*) as global_rows from public.global_data;
select count(*) as egypt_rows from public.egypt_data;
--after insert data
select * from public.global_data limit 5;
select * from public.egypt_data limit 5;
